version: "2"
services:
  telegrambot:
    image: mydict
    container_name: mydictbot
    volumes:
      - /home/pi/dictdata:/var/lib/mydict
    environment:
      - BADGERDB_DIR=/var/lib/mydict
    restart: always
