version: "2"
services:
  telegrambot:
    image: coll97/mydict
    container_name: mydictbot
    volumes:
      - /home/pi/dictdata:/var/lib/mydict
      - /home/pi/backups:/var/bck/mydict
    environment:
      - BADGERDB_DIR=/var/lib/mydict
      - BADGERDB_BCK_DIR=/var/bck/mydict
    restart: always
