version: "2"
services:
  influxdb:
    image: arm32v7/influxdb 
    container_name: influxdb
    restart: always
    ports:
      - 8086:8088
    volumes:
      - ./data/influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword       
      - INFLUXDB_USER=telegraf 
      - INFLUXDB_USER_PASSWORD=secretpassword
  telegrambot:
    image: mydict
    container_name: mydictbot
    restart: always
